# Parameters under each service should be sorted alphabetically.

version: '3.9'

services:
  api:
    build: 
      context: ./api
      target: development
    command: sh -c "daphne --access-log /var/log/api/daphne/access.log --bind 0.0.0.0 core.asgi:application && python manage.py runworker -v2"
    depends_on:
      - celery
    env_file:
      - env_vars/.env_api
    ports:
      - 8000:8000
    restart: 'no'
    volumes:
      - ./api:/app
      - ./persistent_data/log/api/daphne:/var/log/api/daphne
      - ./persistent_data/log/api/django:/var/log/api/django
      - ./persistent_data/media:/var/lib/media
      - ./persistent_data/static:/var/lib/static

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    env_file:
      - env_vars/.env_frontend
    ports:
      - 3000:3000
    restart: always
    volumes:
      - /app/node_modules # hack to not overwrite node_modules in container
      - ./frontend:/app
      - ./persistent_data/log/nginx:/var/log/nginx
      - ./persistent_data/media:/var/lib/media
      - ./persistent_data/static:/var/lib/static

  db:
    env_file:
      - env_vars/.env_db
    image: postgres:14.5
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./persistent_data/pg_data:/var/lib/postgresql/data

  celery:
    build: 
      context: ./api
      target: development
    command: celery --app tasks worker --loglevel INFO
    depends_on:
      - db
      - redis
    env_file:
      - env_vars/.env_api
    restart: 'no'
    volumes:
      - ./api:/app
      - ./persistent_data/log/api/celery:/var/log/api/celery
      - ./persistent_data/media:/var/lib/media
      - ./persistent_data/static:/var/lib/static

  redis:
    image: redis:6.2-buster
    restart: always

  grafana:
    depends_on: 
      - prometheus
    image: grafana/grafana:8.3.6
    ports:
      - 4000:3000
    volumes: 
      - ./persistent_data/grafana:/var/lib/grafana

  prometheus:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
    image: prom/prometheus:v2.33.1
    ports:
      - 9090:9090
    volumes:
      - ./persistent_data/prometheus:/data
      - ./prometheus/:/etc/prometheus
