global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  # TODO: Adjust accordingly.
  - job_name: prometheus

    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true

    static_configs:
      - targets: ['api:8000']
